@startuml
title Text Encoder

class Main {
}

Main --> ArgParser
Main --> Encoder

ArgParser -Up-> StringReader
ArgParser -Up-> StringWriter
ArgParser -Up-> FileReader
ArgParser -Up-> FileWriter
ArgParser -Up-> ConsoleReader
ArgParser -Up-> ConsoleWriter
ArgParser -Up-> Xor
ArgParser -Up-> Cesar
ArgParser -Up-> ScalarEncryptionKey
ArgParser -Up-> IterableEncryptionKey

class ArgParser {
  +get_reader()
  +get_writer()
  +get_coder()
}


class Encoder {
  +encode()
}

Encoder --> Coder

abstract class Coder {
  {abstract}encode_char()
}
Coder <|-- Cesar
Coder <|-- Xor

class Cesar {
  +encode_char()
}
class Xor {
  +encode_char()
}

Encoder --> Reader
Encoder --> Writer

abstract class Reader {
  {abstract} read()
}

abstract class Writer {
  {abstract} write()
  {abstract} finish()
}

Reader <|-- StringReader
Reader <|-- FileReader
Reader <|-- ConsoleReader

class StringReader {
  +read()
}

class FileReader {
  +read()
}

class ConsoleReader {
  +read()
}

Writer <|-- StringWriter
Writer <|-- FileWriter
Writer <|-- ConsoleWriter

class StringWriter {
  +write()
  +get()
}

class FileWriter {
  +write()
  +finish()
}

class ConsoleWriter {
  +write()
  +finish()
}

class EncryptionKey {
  +get()
}

class ScalarEncryptionKey {
  +get()
}

class IterableEncryptionKey {
  +get()
}

Coder -right-> EncryptionKey
EncryptionKey <|-- ScalarEncryptionKey
EncryptionKey <|-- IterableEncryptionKey
@enduml